solarisQ8:
	gcc -Wall asn2.h q8.c libpnm.h -lm -I. -L. -lpnm -o q8
solarisQ9:
	gcc -Wall asn2.h q9.c libpnm.h -lm -I. -L. -lpnm -o q9
solarisQ10:
	gcc -Wall asn2.h q10.c libpnm.h -lm -I. -L. -lpnm -o q10
linuxQ8:
	gcc -Wall asn2.h q8.c libpnm.h libpnm.c -lm -I. -L. -o q8
linuxQ9:
	gcc -Wall asn2.h q9.c libpnm.h libpnm.c -lm -I. -L. -o q9
linuxQ10:
	gcc -Wall asn2.h q10.c libpnm.h libpnm.c -lm -I. -L. -o q10
clean:
	rm q8 q9 q10
